services:
  uni-bot-active:
    build: .
    container_name: uni-bot-active
    restart: always
    
    env_file:
      - .env
      
    volumes:
     - ./bot_state_active.json:/app/bot_state_active.json
     - ./logs:/app/logs